author: Pe4enika
bitmaps:
- bitmaps/00.png
- bitmaps/01.png
- bitmaps/02.png
- bitmaps/03.png
- bitmaps/04.png
- bitmaps/05.png
- bitmaps/06.png
- bitmaps/07.png
- bitmaps/08.png
- bitmaps/09.png
- bitmaps/10.png
- bitmaps/11.png
- bitmaps/12.png
- bitmaps/13.png
- bitmaps/14.png
- bitmaps/15.png
- bitmaps/16.png
- bitmaps/17.png
- bitmaps/18.png
- bitmaps/19.png
- bitmaps/20.png
- bitmaps/21.png
- bitmaps/22.png
- bitmaps/23.png
- bitmaps/24.png
- bitmaps/25.png
- bitmaps/26.png
- bitmaps/27.png
frames:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
name: Star Rain
u1: 30720
u2: 12288